export default [
  {
    latitude: -7.17725,
    longitude: 112.00058,
    district: "Bojonegoro",
    sub_district: "Sumberrejo",
    street_name: "Jl. Raya Puk Sumberrejo",
    street_width: "8",
    sta: "100",
    street_path: "A",
    left_typical: "Trapesium",
    left_drainase_depth: "1.5",
    left_drainase_width: "1.5",
    left_drainase_condiiton: "Perlu cek",
    right_typical: "Bentuk U",
    right_drainase_depth: "1.5",
    right_drainase_width: "1.5",
    right_drainase_condiiton: "Baik",
    note: "Drainase sebelah kiri berupa bronjong dan sebelah kanan tidak ada drainase",
    description: "Antara sta 1 dan sta 2 ada drainase yang terputus oleh jalan",
    is_published: false,
    user_id: 1,
  },
  {
    latitude: -7.17725,
    longitude: 112.00058,
    district: "Bojonegoro",
    sub_district: "Sumberrejo",
    street_name: "Jl. Raya Puk Sumberrejo",
    street_width: "8",
    sta: "100",
    street_path: "A",
    left_typical: "Trapesium",
    left_drainase_depth: "1.5",
    left_drainase_width: "1.5",
    left_drainase_condiiton: "Perlu cek",
    right_typical: "Bentuk U",
    right_drainase_depth: "1.5",
    right_drainase_width: "1.5",
    right_drainase_condiiton: "Baik",
    note: "Drainase sebelah kiri berupa bronjong dan sebelah kanan tidak ada drainase",
    description: "Antara sta 1 dan sta 2 ada drainase yang terputus oleh jalan",
    is_published: false,
    user_id: 2,
  },
];
